# -*- coding: utf-8 -*-
"""Teste_EBAC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13ZNxKmE0CuVoIw4xq_OBpY11_IE1R_xz
"""

num1 = int(input("Enter first number: "))
num2 = int(input("Enter second number: "))

calculator1 = num1 + num2 - 7
calculator2 = calculator1 *(4/3)

print(f"The result of calculator2 is: {calculator2}")

if calculator2 <= 40:
  new_num = float(input("Insert another number: "))
  print(f"The number inserted was: {new_num}")

else:
  print("Agree")